//Approved=false
//DriverEntry
#define fun_DriverEntry DriverEntry
//RiffaEvtDevicePrepareHardware
#define fun_WDF_DEVICE_PREPARE_HARDWARE RiffaEvtDevicePrepareHardware
//RiffaEvtDeviceReleaseHardware
#define fun_WDF_DEVICE_RELEASE_HARDWARE RiffaEvtDeviceReleaseHardware
//RiffaEvtDeviceAdd
#define fun_WDF_DRIVER_DEVICE_ADD RiffaEvtDeviceAdd
//RiffaEvtInterruptDpc
#define fun_WDF_INTERRUPT_DPC RiffaEvtInterruptDpc
//RiffaEvtInterruptIsr
#define fun_WDF_INTERRUPT_ISR RiffaEvtInterruptIsr
//RiffaEvtIoDeviceControl
#define fun_WDF_IO_QUEUE_IO_DEVICE_CONTROL RiffaEvtIoDeviceControl
//RiffaEvtDriverContextCleanup
#define fun_WDF_OBJECT_CONTEXT_CLEANUP RiffaEvtDriverContextCleanup
//RiffaEvtProgramDma
#define fun_WDF_PROGRAM_DMA_1 RiffaEvtProgramDma
//RiffaEvtTimerFunc
#define fun_WDF_TIMER_1 RiffaEvtTimerFunc
